=head1 NAME

MIME::Tools::tricks - cool things to do



=head1 SYNOPSIS

This is part of the MIME-tools documentation.
See L<MIME::Tools> for the full table of contents.



=head1 DESCRIPTION

Try the following techniques to get the most out of MIME-tools.


=head2 Dump entity structure

To see how a parsed entity is really structured, don't just
print it.  Dump the skeletal summary:

    $entity->dump_skeleton(\*STDERR)




=head1 SEE ALSO

See L<MIME::Tools/SYNOPSIS> for the full table of contents.

